baseURL = "https://jakegut.com/"
languageCode = "en-us"
title = "Jake Gutierrez"
theme = "jake-hugo-theme"

googleAnalytics = "UA-113542849-4" 

[markup.goldmark.renderer]
unsafe= true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'monokai'
    tabWidth = 4

[params]
  Name = "Jake Gutierrez"
  GithubID = "jakegut"
  LinkedInID = "jakegut"
  Email = "jakegut0108@gmail.com"
  Subtitle = "Software Engineer at Rivet"

[menu]
  [[menu.header]]
    name = "About"
    weight = 4
    url = "/about"
  [[menu.header]]
    name = "Resume"
    weight = 6
    url = "/resume.pdf"
  
  
