baseURL = "https://jakegut.com/"
languageCode = "en-us"
title = "Jake Gutierrez"
theme = "jake-hugo-theme"

googleAnalytics = "UA-113542849-4" 

PygmentsCodeFences = true
PygmentsStyle = "dracula"

[markup.goldmark.renderer]
unsafe= true

[params]
  Name = "Jake Gutierrez"
  GithubID = "jakeryang"
  LinkedInID = "jakegut"
  Email = "jakegut0108@gmail.com"

[menu]
  [[menu.header]]
    name = "Projects"
    weight = 5
    url = "/projects"
  [[menu.header]]
    name = "Posts"
    weight = 4
    url = "/posts"
  [[menu.header]]
    name = "Resume"
    weight = 6
    url = "/resume.pdf"
  
  