baseURL = "http://example.org/"
languageCode = "en-us"
title = "Jake Gutierrez"
theme = "jake"
PygmentsCodeFences = true

[params]
  Name = "Jake Gutierrez"
  HeaderUsername = "jakerg"
  About = "Test of theme"
  GithubID = "jakeryang"
  LinkedInID = "jakegut"
  Email = "jakegut0108@gmail.com"

[menu]
  [[menu.header]]
    name = "Projects"
    weight = 5
    url = "/projects"
  [[menu.header]]
    name = "Posts"
    weight = 4
    url = "/posts"
  [[menu.header]]
    name = "Resume"
    weight = 6
    url = "/resume.pdf"
  
  