name: Build LaTeX Resume

on:
  push:
    paths:
     - ".github/workflows/build.yml"
     - "**.tex"
     - "**.cls"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Git Repository
        uses: actions/checkout@v1
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          # pre_compile: "tlmgr update --self && tlmgr update --all"
          post_compile: "latexmk -c"
          latexmk_use_xelatex: true
          working_directory: "resume/"
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
      - name: Copy PDF to artifacts and public and Cleanup
        run: |
          cp resume/main.pdf resume/artifacts/resume-${{ steps.date.outputs.date }}.pdf
          cp resume/main.pdf public/resume.pdf

          rm resume/main.pdf
          rm resume/main.xdv
      - name: Push changes to GitHub
        run: |
          git config --local user.name "Jake Gutierrez"
          git config --local user.email "jakegut0108@gmail.com"

          git add .
          git commit -m "[CD] Update resume.pdf"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}